/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/8.0-20221222145522+0000/samples
 */

plugins {
    `capture-cpu-performance`
}

tasks.register("noop")

tasks.register("sleep") {
    dependsOn("noop")
    doLast {
        Thread.sleep(1000 * 10)
    }
}
